repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.3.0 # Use a specific version
  hooks:
    - id: black
      exclude: ".*migrations/.*" # Exclude migration files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.14 # Use a specific version
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      exclude: ".*migrations/.*"
    - id: ruff-format
      exclude: ".*migrations/.*"
