databases:
  - name: book_db_catus
    plan: free
    databaseName: book_db_hrqy
    user: catus

services:
  - type: web
    plan: free
    name: catus_blueprint
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOW_HOSTS
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        sync: false 
      - key: WEB_CONCURRENCY
        value: 4
      - fromGroup: catus_books_env

