databases:
  - name: anjaniadb
    plan: free
    databaseName: romydb 
    user: romeo

services:
  - type: web
    plan: free
    name: catus_blueprint
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: anjaniadb
          property: connectionString 
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: CREATE_SUPERUSER
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
     - key: DJANGO_SUPERUSER_USERNAME
        sync: false
     - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_ALLOW_HOSTS
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        sync: false 
      - key: WEB_CONCURRENCY
        value: 4
      - fromGroup: catus_books_env

