databases:
  - name: book_db_catus
    plan: free
    databaseName: book_db_hrqy
    user: catus

services:
  - type: web
    plan: free
    name: catus_blueprint
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: book_db_catus
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
